server:
  port: 8080
  servlet:
    context-path: /interview
  shutdown: graceful

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:innodb
    username: inno
    password: innopass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
  jackson:
    default-property-inclusion: non_null